# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 01:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('C00', 'Categoria0'), ('C01', 'Categoria1'), ('C02', 'Categoria2'), ('C03', 'Categoria3')], default='C00', max_length=3)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.FilePathField(default='C:\\Users\\Ignacio\\workspace\\CC4401\\tarea3\\Segmentation-Fault-Junkies\\tarea3\\app/static/dummy.png', path='C:\\Users\\Ignacio\\workspace\\CC4401\\tarea3\\Segmentation-Fault-Junkies\\tarea3\\app/static/')),
                ('actividad', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='I', max_length=1)),
                ('formas_de_pago', models.CharField(choices=[('F00', 'Forma0'), ('F01', 'Forma1'), ('F02', 'Forma2'), ('F03', 'Forma3')], default='F00', max_length=3)),
                ('latitud', models.FloatField(null=True)),
                ('longitud', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor_Ambulante',
            fields=[
                ('vendedor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Vendedor')),
            ],
            bases=('app.vendedor',),
        ),
        migrations.CreateModel(
            name='Vendedor_Fijo',
            fields=[
                ('vendedor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Vendedor')),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
            ],
            bases=('app.vendedor',),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vendedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vendedor'),
        ),
    ]
